// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("toggltrack")
	ScopeName = "github.com/zmoog/collector/toggltrack"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
