---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app.kubernetes.io/name: {{.Release.Name}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
spec:
  # Recreate is needed to reset downstream services' persistent connections to
  # outdated, orphaned proxy pods.
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{.Release.Name}}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{.Release.Name}}
        app.kubernetes.io/component: otel-collector
        app.kubernetes.io/part-of: hosted-otel-collector
        app.kubernetes.io/version: {{ .Chart.AppVersion }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      # nodeSelector:
      #   infra.k8s.elastic.co/hardware-profile: {{.Values.labels.hardware_profile}}
      securityContext:
        runAsNonRoot: true
      containers:
      - name: otel-collector
        ports:
        - name: health
          containerPort: 13133
        image: "{{ $.Values.image.registry }}:{{ $.Values.image.tag | default "latest" }}"
        args:
          - '--config=/etc/config/collector-config.yaml'
        volumeMounts:
        - name: collector-config
          mountPath: /etc/config
          readOnly: true
        livenessProbe:
          httpGet:
            path: /
            port: 13133
        readinessProbe:
          httpGet:
            path: / 
            port: 13133
        resources:
{{ toYaml .Values.resources | indent 10 }}
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
              - "ALL"
      imagePullSecrets:
      - name: elastic-docker-registry
      volumes:
      - name: collector-config
        configMap:
          name: {{.Release.Name}}-collector-config
