apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: otel-collector-system

spec:
  selector:
    matchLabels:
      app: otel-collector

  replicas: 1

  strategy:
    type: Recreate

  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true

      containers:
      - name: otel-collector
        resources:
          requests:
            cpu: 1500m
            memory: 128Mi
          limits:
            cpu: 1500m
            memory: 128Mi