linters:
  enable:
    - gofmt
    - govet
    - golint
    - gosimple
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - errorlint
    - gocritic
    - gosec

run:
  deadline: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec