// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("shellycloud")
	ScopeName = "github.com/zmoog/collector/shellycloud"
)

const (
	MetricsStability = component.StabilityLevelDevelopment
)
