# builder-config.yaml
dist:
  module: github.com/zmoog/collector/collector
  name: collector
  description: OTel Collector distribution
  output_path: .
  version: 0.5

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.130.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.130.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/elasticsearchexporter v0.130.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.130.0

receivers:
  - gomod:
      github.com/zmoog/collector/receiver/toggltrackreceiver v0.130.0
  - gomod:
      github.com/zmoog/collector/receiver/zcsazzurroreceiver v0.130.0
  - gomod:
      github.com/zmoog/collector/receiver/wavinsentioreceiver v0.130.0

extensions:
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/basicauthextension v0.130.0
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.130.0

replaces:
  - github.com/zmoog/collector/receiver/toggltrackreceiver v0.130.0 => ../receiver/toggltrackreceiver
  - github.com/zmoog/collector/receiver/wavinsentioreceiver v0.130.0 => ../receiver/wavinsentioreceiver
  - github.com/zmoog/collector/receiver/zcsazzurroreceiver v0.130.0 => ../receiver/zcsazzurroreceiver
