# config.yaml
receivers:
  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/azureeventhubreceiver
  #   connection: ${EVENTHUB_CONNECTION_STRING}
  # toggltrack:
  #   interval: 30m
  #   api_token: ${TOGGL_API_TOKEN}
  zcsazzurro:
    interval: 5m
    client_id: ${ZCS_CLIENT_ID}
    auth_key: ${ZCS_AUTH_KEY}
    thing_key: ${ZCS_THING_KEY}
processors:
  batch:

exporters:
  # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
  debug:
    verbosity: detailed

  # https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/elasticsearchexporter
  elasticsearch:
    endpoints: ${ELASTICSEARCH_ENDPOINTS}
    logs_index: logs-toggl.track-default
    metrics_index: metrics-zcs.azzurro-default
    auth:
      authenticator: basicauth

extensions:
  basicauth:
    client_auth:
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}

service:
  extensions: [basicauth]
  pipelines:
    # logs:
    #   receivers: [toggltrack]
    #   processors: [batch]
    #   exporters: [elasticsearch, debug]
    metrics:
      receivers: [zcsazzurro]
      exporters: [elasticsearch, debug]
  telemetry:
    logs:
      level: debug
