name: Receiver Tests

on:
  push:
    paths:
      - 'receiver/**'
      - '.github/workflows/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'receiver/**'
      - '.github/workflows/**'
    branches: [ main ]

jobs:
  test:
    name: Lint and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        receiver: [toggltrackreceiver, zcsazzurroreceiver]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'
        cache: true

    - name: Install golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60.0

    - name: Lint
      run: |
        cd receiver/${{ matrix.receiver }}
        golangci-lint run ./...

    - name: Test
      run: |
        cd receiver/${{ matrix.receiver }}
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./receiver/${{ matrix.receiver }}/coverage.txt
        flags: ${{ matrix.receiver }}
        name: ${{ matrix.receiver }}